### ISSUE TITLE
related compute coverage

### ISSUE THREAD

**Issue by sanghoon-e** [the-themis-benchmarks/home#10]
Hello, 

Now, I am trying the themis refer [README](https://github.com/the-themis-benchmarks/home/blob/master/README.md) file. 
(on VM machine usnig your image)
I run monkey and `check_crash.py` script successfully.

However, when I run `compute_coverage.py` script using below command, 
`python3 compute_coverage.py -o ../monkey-results --monkey --app ActivityDiary --id \#118 --acc_csv`

I met error like below. 
```
Exception in thread "main" java.io.FileNotFoundException: ../ActivityDiary/ActivityDiary-#118/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:224)
at org.jacoco.cli.internal.commands.Report.analyze(Report.java:110)
at org.jacoco.cli.internal.commands.Report.execute(Report.java:84)
at org.jacoco.cli.internal.Main.execute(Main.java:90)
at org.jacoco.cli.internal.Main.main(Main.java:105)
```

It seems to be related java classes files. 

I would appreciate it if you could let me know if there is a place I missed or if there is a guide that I can refer to.

Thanks

**Comment by tingsu** [comment]
@sanghoon-e  Thank you for letting me this issue. 

 I suggest you to take a look at the logic of ``compute_coverage.py``. You will find that computing code coverage requires the app are instrumented by Jacoco. So, to avoid this issue (if you indeed hope to obtain code coverage), you need to instrument and compile the buggy app source code version.  To facilitate this usage of our benchmark, you can download the instrumented buggy app version by referring to this file [PROJECTS.md](https://github.com/the-themis-benchmarks/home/blob/master/PROJECTS.md). In that list, we have provided most of compiled source code (including the java class files). Note that you may have to recompile the app source code on your machine or the VM machine because the provided app version (including the java class files) are compiled on our own machine.  We did not provide the compiled code in the VM to avoid too large VM size.

let me know if you still have problems.

**Comment by sanghoon-e** [comment]
@tingsu thanks for kind reply. 

Yes, I already checked `compute_coverage.py`. 
So I want to know how to get source codes of built apks which included each application directory. 

After reading your reply, I realized I missed the [PROJECTS.md](https://github.com/the-themis-benchmarks/home/blob/master/PROJECTS.md).

Thanks Again 👍

**Comment by tingsu** [comment]
You are welcome. Thank you for trying Themis. I will close close this issue.
